# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>
  MG_USERNAME: <%= ENV["MG_USERNAME"] %>
  MG_PASSWORD: <%= ENV["MG_PASSWORD"] %>
# MANDRILL_USERNAME: horndavidg@gmail.com
# MANDRILL_PASSWORD: lhmJEplppEd59bp6m4HG2A
  FACEBOOK_ID: <%= ENV["FACEBOOK_ID"] %>
  FACEBOOK_SECRET: <%= ENV["FACEBOOK_SECRET"] %>
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PRO"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  MG_USERNAME: <%= ENV["MG_USERNAME"] %>
  MG_PASSWORD: <%= ENV["MG_PASSWORD"] %>
  FACEBOOK_ID: <%= ENV["FACEBOOK_ID"] %>
  FACEBOOK_SECRET: <%= ENV["FACEBOOK_SECRET"] %>